//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLister.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public decimal Price { get; set; }
        public int YearId { get; set; }
        public string PicUrl { get; set; }
        public string PicPath { get; set; }
        public int MakeId { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Year Year { get; set; }
    }
}
